#!/usr/bin/env bash
# This script installs and sets up nginx web server on our server

apt update -y && apt upgrade -y
apt install nginx -y

echo "Hello World!" >/var/www/html/index.nginx-debian.html

service nginx restart
