#!/usr/bin/env bash
# This script installs and sets up nginx web server on our server and
# handles redirections and 404 errors
# adds a custome response header

apt update -y && apt upgrade -y
apt install nginx -y

echo "Hello World!" >/var/www/html/index.nginx-debian.html

sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default


curl https://pastebin.com/raw/szLjiB9Q >/var/www/html/404.html
sed -i '/QH2-TGUlwu4 permanent;$/a\        error_page 404 /404.html;' /etc/nginx/sites-available/default

sed -i "/404 \/404.html;$/a\        add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

service nginx restart
