#!/bin/bash
# This script installs and configures HAproxy on the lb-01 server
# Install HAproxy
apt update -y
apt install -y haproxy

# Configure HAproxy
haproxy_config="\nbackend web-backend\n\tbalance roundrobin\n\tserver 323054-web-01 107.23.94.198:80 check\n\tserver 323054-web-02 35.175.64.25:80 check\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"

echo -e "$haproxy_config" >>/etc/haproxy/haproxy.cfg

# Enable HAproxy service
systemctl enable haproxy

# Start HAProxy service
systemctl start haproxy
