#!/bin/bash
# This script installs and configures HAproxy on the lb-01 server
# Install HAproxy
apt update -y && apt upgrade -y
apt install -y haproxy

# Configure HAproxy
haproxy_config="frontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tmode http\n\tbalance roundrobin\n\tserver web-01 323054-web-01:80 check\n\tserver web-02 323054-web-02:80 check\n"

echo -e "$haproxy_config" >>/etc/haproxy/haproxy.cfg

# Enable HAproxy service
systemctl enable haproxy

# Start HAProxy service
systemctl start haproxy
