#!/usr/bin/env bash
# This script fixes the second web stack debugging_1 server written shortly
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
rm /run/nginx.pid
