#!/usr/bin/env bash
# This script accomplishes several tasks.

echo $$ > /var/run/myscript.pid

trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command; rm -f /var/run/myscript.pid; exit" SIGTERM
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT


while ((1)); do
	echo "To infinity and beyond"
	sleep 2

done
