#!/usr/bin/env bash
# This script configures Nginx to serve your page from the route /airbnb-onepage/
server {
    listen 80;
    server_name 127.0.0.1 107.23.94.198;

    location /airbnb-onepage/ {
        include proxy_params;
	proxy_pass http://localhost:5000/airbnb-onepage/;
    }
}
